apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "contact@thomas-illiet.fr"
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - dns01:
        selector:
          matchLabels:
            use-cloudflare-solver: "true"
        cloudflare:
          email: contact@thomas-illiet.fr
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key


